# Generated by Django 5.2.5 on 2025-08-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='us', max_length=255),
            preserve_default=False,
        ),
    ]
